services:
    mcp-lecture:
        build:
            context: ./web
            dockerfile: Dockerfile
        image: mcp-ya-ho-lecture:latest
        container_name: mcp-ya-ho-lecture
        ports:
            - "3333:80"
        restart: unless-stopped
